#!/usr/bin/env python3
# Generated by openfoam-sediment-installer
"""Export OpenFOAM data and make physical-time VisIt manifests (stdlib only)."""

from __future__ import annotations

import argparse
from decimal import Decimal, InvalidOperation
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

_VTK_TIME_HEADER = re.compile(r"^(?:TIME|TimeValue)\s+1\s+1\s+(?:float|double)\s*$")


def _physical_time(value: object) -> Decimal:
    try:
        if isinstance(value, bool):
            raise InvalidOperation
        time = Decimal(str(value))
    except (InvalidOperation, ValueError) as error:
        raise ValueError(f"Invalid physical time: {value!r}") from error
    if not time.is_finite():
        raise ValueError(f"Non-finite physical time: {value!r}")
    return time


def _write_manifest(output: Path, samples: list[tuple[Decimal, Path]]) -> Path:
    if not samples:
        raise ValueError(f"No timesteps for {output}")
    if len({time for time, _ in samples}) != len(samples):
        raise ValueError(f"Duplicate physical times for {output}; do not mix datasets")
    samples.sort(key=lambda sample: sample[0])
    contents = "!NBLOCKS 1\n" + "".join(
        f"!TIME {time}\n{file.relative_to(output.parent).as_posix()}\n"
        for time, file in samples
    )
    if output.is_symlink():
        raise ValueError(f"Refusing to overwrite a symlink: {output}")
    if output.exists() and output.read_text(encoding="utf-8") != contents:
        raise ValueError(f"Existing manifest differs: {output}; move it aside to regenerate")
    if not output.exists():
        output.write_text(contents, encoding="utf-8")
    return output


def manifest_from_series(series_path: Path) -> Path:
    """Keep actual OpenFOAM time values, not numbered-file indices."""
    series_path = Path(series_path)
    if series_path.is_symlink():
        raise ValueError(f"Refusing a symlinked series file: {series_path}")
    series_path = series_path.resolve()
    data = json.loads(series_path.read_text(encoding="utf-8"), parse_float=Decimal)
    if (not isinstance(data, dict) or data.get("file-series-version") != "1.0"
            or not isinstance(data.get("files"), list)):
        raise ValueError(f"Unrecognized OpenFOAM VTK series: {series_path}")
    samples = []
    for sample in data["files"]:
        if not isinstance(sample, dict) or not isinstance(sample.get("name"), str):
            raise ValueError(f"Malformed sample in {series_path}")
        vtk_file = (series_path.parent / sample["name"]).resolve()
        if not vtk_file.is_relative_to(series_path.parent):
            raise ValueError(f"VTK series points outside its directory: {vtk_file}")
        if vtk_file.suffix != ".vtk" or not vtk_file.is_file():
            raise ValueError(f"Missing legacy VTK sample: {vtk_file}")
        samples.append((_physical_time(sample.get("time")), vtk_file))
    output = series_path.with_name(series_path.name.removesuffix(".vtk.series") + ".visit")
    return _write_manifest(output, samples)


def time_from_ascii_vtk(vtk_path: Path) -> Decimal:
    """Fallback reads explicit FIELD time, never modification time/filename."""
    with Path(vtk_path).open("r", encoding="ascii", errors="strict") as source:
        if not source.readline().startswith("# vtk DataFile Version"):
            raise ValueError(f"Not a legacy VTK file: {vtk_path}")
        source.readline()  # Title, not a reliable physical-time representation.
        if source.readline().strip() != "ASCII":
            raise ValueError(f"Fallback requires ASCII VTK data: {vtk_path}")
        for line in source:
            if _VTK_TIME_HEADER.match(line.strip()):
                for value_line in source:
                    if value_line.strip():
                        return _physical_time(value_line.strip())
    raise ValueError(
        f"No explicit TIME/TimeValue metadata in {vtk_path}. Export .vtk.series "
        "metadata; physical time must not be inferred from modification dates."
    )


def make_manifests(export_root: Path) -> list[Path]:
    export_root = Path(export_root).resolve()
    series = sorted(export_root.rglob("*.vtk.series"))
    if series:
        return [manifest_from_series(path) for path in series]
    # Group an OpenCFD numbered sequence only after reading its physical time.
    # Patch files live in separate directories and receive separate manifests.
    groups: dict[tuple[Path, str], list[tuple[Decimal, Path]]] = {}
    for vtk_file in sorted(export_root.rglob("*.vtk")):
        stem = re.sub(r"_\d+$", "", vtk_file.stem)
        groups.setdefault((vtk_file.parent, stem), []).append(
            (time_from_ascii_vtk(vtk_file), vtk_file)
        )
    if not groups:
        raise ValueError(f"No legacy VTK output found in {export_root}")
    return [_write_manifest(parent / f"{stem}.visit", samples)
            for (parent, stem), samples in sorted(groups.items())]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("case", type=Path, help="OpenFOAM case directory")
    parser.add_argument("--output", default="VTK-VisIt", help="export subdirectory name")
    parser.add_argument("--manifest-only", action="store_true", help="use existing legacy VTK export")
    args = parser.parse_args(argv)
    case = args.case.resolve()
    if not (case / "system" / "controlDict").is_file():
        parser.error(f"Not an OpenFOAM case: {case}")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", args.output):
        parser.error("--output must be a simple subdirectory name")
    export_root = case / args.output
    if export_root.is_symlink():
        parser.error(f"Refusing a symlinked export directory: {export_root}")
    try:
        if not args.manifest_only:
            executable = shutil.which("foamToVTK")
            if executable is None:
                raise ValueError("Activate the installed OpenFOAM v2406 environment first")
            subprocess.run(
                [executable, "-case", str(case), "-legacy", "-ascii", "-poly-decomp",
                 "-name", args.output], check=True,
            )
        for manifest in make_manifests(export_root):
            print(manifest)
        return 0
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"Post-processing failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
